Traceback (most recent call last):
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/thomasmonks/opt/anaconda3/envs/hds_python/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
number = 1
if number > 2:
print("Number > 2!")
else:
print("Number <=2")
------------------

[0;36m  File [0;32m"<ipython-input-3-44d8c9689021>"[0;36m, line [0;32m3[0m
[0;31m    print("Number > 2!")[0m
[0m    ^[0m
[0;31mIndentationError[0m[0;31m:[0m expected an indented block

IndentationError: expected an indented block (<ipython-input-3-44d8c9689021>, line 3)

